### ISSUE TITLE
Missing getParentLogger() in com.jenkov.db.jdbc.SimpleDataSource

### ISSUE THREAD

**Issue by anniehall006** [jjenkov/butterfly-persistence#2]
when using Java 1.7 (new method added in javax.sql.CommonDataSource)

**Comment by jjenkov** [comment]
Oh, sorry about that! 

I guess Butterfly Persistence could use an upgrade to Java 8 or Java 11 ...

**Comment by jjenkov** [comment]
Upgrade coming soon :-D

**Comment by jjenkov** [comment]
This has been fixed
