### ISSUE TITLE
Where I can find the document about this framework? I want to learn how to use it. Thanks.

### ISSUE THREAD

**Issue by ultrasmooth** [jjenkov/butterfly-persistence#3]

**Comment by jjenkov** [comment]
Hi, I used to have the documentation on its own website, but it should be moved into my tutorial website, http://tutorials.jenkov.com . It has not yet been copied there, though. 

Any special reason you want to learn to use this framework? Honestly, I kinda thought everyone were on the Hibernate / JPA  wagon, or was perhaps using Ibatis / Mybatis by now...

**Comment by chowe991** [comment]
Jenkov - just so you know, I've worked at million-dollar companies that use Butterfly. It is alive and well. It is by far the best way to interact with a database that I've ever worked with. Please don't abandon it.

**Comment by jjenkov** [comment]
Okay... I didn't know anyone was using Butterfly anymore. I don't like its name though - "Butterfly" :-) ... it was a name I used for a group of open source toolkits that were supposed to be "lightweight" - like butterflies :-D ... but I realized over time, that as you add more functionality to a toolkit, it becomes less and less "lightweight". So now I would like to find another name for this little suite of tools instead. I also have a dependency injection container which actually works reasonably well.

**Comment by chowe991** [comment]
Oh, it totally is lightweight in comparison to other frameworks I've worked with. Super easy and straight-forward. You can customize it to fit your needs, too. I love it. In fact, if I'm working with Java, I won't use anything else if the decision is mine to make.

**Comment by jjenkov** [comment]
Should I make an effort soon to resurrect the documentation for Butterfly Persistence? And perhaps make a release of it or something? 

BTW - I have actually considered rebranding Butterfly Persistence to make it part of another toolkit "series" I am (or - at least think I will be) working on soon. Then the name would change, maybe the internal design would be cleaned up a bit - but the main ideas would stay the same. 

The same applies to my Butterfly Dependency Injection Container. Rebranding - a bit of internal design clean up, and then released again. I might do that. Not yet 100% sure about the exact "strategy", but getting there :-)

**Comment by jjenkov** [comment]
The Butterfly Persistence documentation is now finally online! :-)

http://tutorials.jenkov.com/butterfly-persistence/index.html
